/**
 * EXP-AG7: Agent Provenance Trust Scorer
 *
 * Hypothesis: "If we track per-agent provenance (human, codex, claude, cursor, custom-bot)
 * and correlate it with historical gate outcomes (false positives, reverts, hotfixes),
 * then we can dynamically adjust risk thresholds per agent, because some AI models
 * consistently produce higher-quality output than others, and human authors have
 * established reliability patterns."
 *
 * This is different from EXP-AG1 (trust scorer) which focuses on repo-level trust.
 * This is agent-specific: it answers "How much should we trust THIS author?"
 *
 * Deliverable: Pure TypeScript module that computes agent trust scores
 * and suggests threshold adjustments for Trailhead gate evaluation.
 *
 * Date: 2026-05-27
 * Author: Tesla (rd-satellite)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ProvenanceType = "human" | "codex" | "claude" | "cursor" | "custom-bot" | "unknown";

export interface AgentOutcomeRecord {
  id: string;
  agentId: string; // e.g., "rd-satellite", "frontend-dev", "claude-code-session-123"
  provenanceType: ProvenanceType;
  repo: string;
  evaluationId: string;
  gateDecision: "allow" | "warn" | "block";
  actualOutcome: "success" | "revert" | "hotfix" | "no_incident"; // post-deployment outcome
  riskScore: number;
  timestamp: string;
}

export interface AgentTrustMetrics {
  agentId: string;
  provenanceType: ProvenanceType;
  totalReviews: number;
  falsePositives: number; // Flagged as risky but deployed successfully
  truePositives: number; // Flagged as risky and actually caused issues
  falseNegatives: number; // Not flagged but caused issues (escape)
  reverts: number;
  hotfixes: number;
  escapeRate: number; // falseNegatives / (falseNegatives + truePositives)
  falsePositiveRate: number; // falsePositives / (falsePositives + truePositives)
  trustBand: "high" | "medium" | "low" | "untrusted";
  recommendedThresholdAdjustment: number; // Positive = raise threshold (be more strict), negative = lower
}

// ---------------------------------------------------------------------------
// Core Logic
// ---------------------------------------------------------------------------

/**
 * Classify provenance from PR metadata or commit author
 */
export function classifyProvenance(
  author: string,
  prTitle?: string,
  labels?: string[],
): ProvenanceType {
  const authorLower = author.toLowerCase();
  const titleLower = (prTitle || "").toLowerCase();
  const labelsLower = (labels || []).map((l) => l.toLowerCase());

  // Check labels first (most explicit)
  if (labelsLower.includes("provenance:human")) return "human";
  if (labelsLower.includes("provenance:codex")) return "codex";
  if (labelsLower.includes("provenance:claude")) return "claude";
  if (labelsLower.includes("provenance:cursor")) return "cursor";
  if (labelsLower.includes("provenance:agent")) return "custom-bot";

  // Check author patterns
  if (authorLower.includes("dependabot")) return "human"; // Dependabot is trusted
  if (authorLower.includes("github-actions")) return "human"; // CI automation
  if (authorLower.includes("codex")) return "codex";
  if (authorLower.includes("claude")) return "claude";
  if (authorLower.includes("cursor")) return "cursor";
  if (authorLower.includes("komatik") || authorLower.includes("agent")) return "custom-bot";

  // Check title patterns
  if (titleLower.includes("generated by codex")) return "codex";
  if (titleLower.includes("claude")) return "claude";
  if (titleLower.includes("cursor")) return "cursor";

  return "unknown";
}

/**
 * Compute trust metrics for a single agent from historical outcomes
 */
export function computeAgentTrustMetrics(
  records: AgentOutcomeRecord[],
  agentId: string,
): AgentTrustMetrics | null {
  const agentRecords = records.filter((r) => r.agentId === agentId);

  if (agentRecords.length === 0) return null;

  const provenanceType = agentRecords[0].provenanceType;

  let falsePositives = 0;
  let truePositives = 0;
  let falseNegatives = 0;
  let reverts = 0;
  let hotfixes = 0;

  for (const record of agentRecords) {
    const wasFlagged = record.gateDecision === "warn" || record.gateDecision === "block";
    const hadIssues =
      record.actualOutcome === "revert" || record.actualOutcome === "hotfix";

    if (wasFlagged && !hadIssues) {
      falsePositives++;
    } else if (wasFlagged && hadIssues) {
      truePositives++;
    } else if (!wasFlagged && hadIssues) {
      falseNegatives++;
    }

    if (record.actualOutcome === "revert") reverts++;
    if (record.actualOutcome === "hotfix") hotfixes++;
  }

  const totalReviews = agentRecords.length;
  const escapeRate =
    falseNegatives + truePositives > 0
      ? falseNegatives / (falseNegatives + truePositives)
      : 0;
  const falsePositiveRate =
    falsePositives + truePositives > 0
      ? falsePositives / (falsePositives + truePositives)
      : 0;

  // Assign trust band based on multiple signals
  let trustBand: AgentTrustMetrics["trustBand"] = "untrusted";
  if (totalReviews >= 20 && escapeRate < 0.05 && falsePositiveRate < 0.1) {
    trustBand = "high";
  } else if (totalReviews >= 10 && escapeRate < 0.15 && falsePositiveRate < 0.25) {
    trustBand = "medium";
  } else if (totalReviews >= 5) {
    trustBand = "low";
  }

  // Calculate recommended threshold adjustment
  // Positive = raise threshold (be more strict for this agent)
  // Negative = lower threshold (be more lenient for this agent)
  let recommendedThresholdAdjustment = 0;

  switch (trustBand) {
    case "high":
      // Trusted agent: lower threshold by 10-15 points (be more permissive)
      recommendedThresholdAdjustment = -12;
      break;
    case "medium":
      // Moderate trust: adjust by -5 (slightly more permissive)
      recommendedThresholdAdjustment = -5;
      break;
    case "low":
      // Low trust: raise threshold by 10 (be more strict)
      recommendedThresholdAdjustment = 10;
      break;
    case "untrusted":
      // No data or poor track record: default to standard or stricter
      recommendedThresholdAdjustment = 0;
      break;
  }

  // Penalize for escapes (false negatives are worse than false positives)
  if (escapeRate > 0.1) {
    recommendedThresholdAdjustment += 15;
  } else if (escapeRate > 0.05) {
    recommendedThresholdAdjustment += 8;
  }

  return {
    agentId,
    provenanceType,
    totalReviews,
    falsePositives,
    truePositives,
    falseNegatives,
    reverts,
    hotfixes,
    escapeRate: Math.round(escapeRate * 1000) / 10,
    falsePositiveRate: Math.round(falsePositiveRate * 1000) / 10,
    trustBand,
    recommendedThresholdAdjustment,
  };
}

/**
 * Compute trust metrics for all agents in the dataset
 */
export function computeAllAgentTrustMetrics(
  records: AgentOutcomeRecord[],
): AgentTrustMetrics[] {
  const agentIds = [...new Set(records.map((r) => r.agentId))];

  return agentIds
    .map((agentId) => computeAgentTrustMetrics(records, agentId))
    .filter((m): m is AgentTrustMetrics => m !== null)
    .sort((a, b) => {
      // Sort by trust band (high first) then by escape rate (lower is better)
      const bandOrder = { high: 0, medium: 1, low: 2, untrusted: 3 };
      const bandDiff = bandOrder[a.trustBand] - bandOrder[b.trustBand];
      if (bandDiff !== 0) return bandDiff;
      return a.escapeRate - b.escapeRate;
    });
}

/**
 * Generate tuning recommendations based on agent trust metrics
 */
export interface AgentTuningRecommendation {
  agentId: string;
  provenanceType: ProvenanceType;
  trustBand: string;
  currentThreshold: number;
  recommendedThreshold: number;
  reason: string;
  confidence: "high" | "medium" | "low";
  samples: number;
}

export function generateAgentTuningRecommendations(
  metrics: AgentTrustMetrics[],
  baseThreshold: number = 70,
): AgentTuningRecommendation[] {
  return metrics
    .filter((m) => m.trustBand !== "untrusted")
    .map((m) => {
      const recommendedThreshold = Math.max(
        30,
        Math.min(95, baseThreshold + m.recommendedThresholdAdjustment),
      );

      let reason = "";
      switch (m.trustBand) {
        case "high":
          reason = `High trust agent (${m.escapeRate}% escape rate, ${m.falsePositiveRate}% FP rate). Recommend lowering threshold to reduce review noise.`;
          break;
        case "medium":
          reason = `Moderate trust (${m.totalReviews} reviews). Slight threshold reduction recommended.`;
          break;
        case "low":
          reason = `Low trust agent (${m.escapeRate}% escape rate). Increase threshold for stricter review.`;
          break;
      }

      if (m.escapeRate > 0.1) {
        reason += ` WARNING: High escape rate — consider manual review for this agent.`;
      }

      return {
        agentId: m.agentId,
        provenanceType: m.provenanceType,
        trustBand: m.trustBand,
        currentThreshold: baseThreshold,
        recommendedThreshold,
        reason,
        confidence:
          m.totalReviews >= 20
            ? "high"
            : m.totalReviews >= 10
              ? "medium"
              : "low",
        samples: m.totalReviews,
      };
    });
}

/**
 * Generate YAML snippet for .trailhead.yml agent-specific thresholds
 */
export function generateAgentThresholdsYaml(
  recommendations: AgentTuningRecommendation[],
  repo?: string,
): string {
  const lines = [
    "# Trailhead agent-specific threshold tuning",
    `# Generated for ${repo ?? "all repos"}`,
    "schema_version: 2",
    "",
    "agents:",
  ];

  if (recommendations.length === 0) {
    lines.push("  # No agent-specific tuning recommendations");
    return lines.join("\n");
  }

  for (const rec of recommendations) {
    lines.push(`  ${rec.agentId}:`);
    lines.push(`    risk_threshold: ${rec.recommendedThreshold}`);
    lines.push(`    # ${rec.trustBand} trust (${rec.provenanceType})`);
    lines.push(`    # ${rec.confidence} confidence (${rec.samples} samples)`);
    lines.push(`    # ${rec.reason.slice(0, 80)}...`);
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Example Usage & Test Data
// ---------------------------------------------------------------------------

/**
 * Example test data showing how this would work in practice
 */
export const EXAMPLE_RECORDS: AgentOutcomeRecord[] = [
  {
    id: "rec-1",
    agentId: "rd-satellite",
    provenanceType: "custom-bot",
    repo: "KomatikAI/trailhead",
    evaluationId: "eval-001",
    gateDecision: "allow",
    actualOutcome: "success",
    riskScore: 25,
    timestamp: "2026-05-20T10:00:00.000Z",
  },
  {
    id: "rec-2",
    agentId: "rd-satellite",
    provenanceType: "custom-bot",
    repo: "KomatikAI/trailhead",
    evaluationId: "eval-002",
    gateDecision: "warn",
    actualOutcome: "success",
    riskScore: 65,
    timestamp: "2026-05-21T10:00:00.000Z",
  },
  {
    id: "rec-3",
    agentId: "frontend-dev",
    provenanceType: "human",
    repo: "KomatikAI/trailhead",
    evaluationId: "eval-003",
    gateDecision: "allow",
    actualOutcome: "success",
    riskScore: 15,
    timestamp: "2026-05-22T10:00:00.000Z",
  },
  {
    id: "rec-4",
    agentId: "claude-session-123",
    provenanceType: "claude",
    repo: "KomatikAI/trailhead",
    evaluationId: "eval-004",
    gateDecision: "warn",
    actualOutcome: "hotfix",
    riskScore: 55,
    timestamp: "2026-05-23T10:00:00.000Z",
  },
];

/**
 * Demo: Show how to use this module
 */
export function demo(): void {
  console.log("=== Agent Trust Scorer Demo ===\n");

  // Compute metrics for a specific agent
  const rdSatelliteMetrics = computeAgentTrustMetrics(EXAMPLE_RECORDS, "rd-satellite");
  console.log("rd-satellite metrics:", JSON.stringify(rdSatelliteMetrics, null, 2));

  // Compute all agent metrics
  const allMetrics = computeAllAgentTrustMetrics(EXAMPLE_RECORDS);
  console.log("\nAll agent metrics:");
  for (const m of allMetrics) {
    console.log(`  ${m.agentId}: ${m.trustBand} trust (escape: ${m.escapeRate}%, FP: ${m.falsePositiveRate}%)`);
  }

  // Generate recommendations
  const recommendations = generateAgentTuningRecommendations(allMetrics);
  console.log("\nThreshold recommendations:");
  for (const rec of recommendations) {
    console.log(`  ${rec.agentId}: ${rec.currentThreshold} → ${rec.recommendedThreshold} (${rec.reason.slice(0, 60)}...)`);
  }

  // Generate YAML
  const yaml = generateAgentThresholdsYaml(recommendations, "KomatikAI/trailhead");
  console.log("\nGenerated .trailhead.yml snippet:");
  console.log(yaml);
}

// Run demo if executed directly
if (require.main === module) {
  demo();
}
